# Generated by Django 4.2.13 on 2024-06-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_created_at_alter_post_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
